version: '3.8'

services:
  frontend:
    image: ecommerce_frontend:devel 
    command: poetry run gunicorn ecommerce_tcc.app:app --bind 0.0.0.0:5000 
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=$FLASK_APP
      - FLASK_ENV=$FLASK_ENV
      - BACKEND_URL=$BACKEND_URL
    depends_on:
      - backend

  backend:
    image: ecommerce_backend:devel
    command: poetry run uvicorn ecommerce_tcc.entrypoints.api:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRE_HOST=$POSTGRE_HOST
    depends_on:
      - db_migration

  db_migration:
    image: ecommerce_backend:devel
    command: poetry run alembic upgrade head
    environment:
      - DATABASE_URL=$DATABASE_URL
    volumes:
      - ./backend/alembic/versions:/code/alembic/versions
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

volumes:
  postgres_data: 