version: '3.8'

services:
  frontend:
    image: ecommerce_frontend:devel 
    command: poetry run gunicorn ecommerce_tcc.app:app --bind 0.0.0.0:5000 
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    image: ecommerce_backend:devel
    command: poetry run uvicorn ecommerce_tcc.entrypoints.api:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce 
      - POSTGRES_PORT=5432
      - POSTGRE_HOST=db
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce 

volumes:
  postgres_data: 