version: '3.8'

services:
  backend:
    image: ecommerce_tcc:devel
    command: poetry run uvicorn ecommerce_tcc.api:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce 

volumes:
  postgres_data: 