"""empty message

Revision ID: b05f4e6d4829
Revises: 
Create Date: 2023-03-20 20:09:31.102717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05f4e6d4829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
